/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package securevote;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.ListModel;

/**
 * Γραφικό περιβάλλον της εφαρμογής. Δημιουργήθηκε με τη βοήθεια του netbeans
 */
public class Vote extends javax.swing.JPanel {
    //SecureVote svote;
    /**
     * Creates new form Vote
     */
    public Vote() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StartVoting = new javax.swing.JButton();
        EndVoting = new javax.swing.JButton();
        VoteNow = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        username = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CanditateList = new javax.swing.JList<>();
        PostVote = new javax.swing.JButton();

        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        StartVoting.setText("Εκκινηση Ψηφοφορίας");
        StartVoting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartVotingActionPerformed(evt);
            }
        });

        EndVoting.setText("Λήξη Ψηφοφορίας");
        EndVoting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EndVotingActionPerformed(evt);
            }
        });

        VoteNow.setText("Θέλω να ψηφίσω");
        VoteNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoteNowActionPerformed(evt);
            }
        });

        jLabel1.setText("Ψηφοδέλτιο");

        Title.setText("ΕΚΛΟΓΕΣ");

        jLabel3.setText("Όνομα:");

        jLabel4.setText("Κωδικός:");

        CanditateList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(CanditateList);

        PostVote.setText("Κατάθεση Ψηφοδελτίου");
        PostVote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PostVoteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(2, 2, 2)
                        .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(1, 1, 1)
                        .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VoteNow))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(StartVoting)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EndVoting))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PostVote))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(223, 223, 223)
                                .addComponent(Title)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StartVoting)
                    .addComponent(EndVoting))
                .addGap(12, 12, 12)
                .addComponent(Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VoteNow)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PostVote)
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        System.out.println("FOCUS");
        // Αλαγή τίτλου για τις εκλογές σύμφωνα με το αρχείο του ψηφοδελτίου
        Title.setText(SecureVote.electionTitle);        
        Title.repaint();
        // Προσθήκη των υποψηφίων στη λίστα του ψηφοδελτίου
        DefaultListModel canditates= new DefaultListModel();
        for (var c: SecureVote.candidate){
            canditates.addElement(c);
        }
        CanditateList.setModel(canditates);
        CanditateList.setVisible(false);
        CanditateList.repaint();
        VoteNow.setEnabled(false);
        PostVote.setEnabled(false);
        EndVoting.setEnabled(false);
        this.repaint();
    }//GEN-LAST:event_formAncestorAdded

    private void StartVotingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartVotingActionPerformed
        JPasswordField pwd = new JPasswordField();
        int action = JOptionPane.showConfirmDialog(this, pwd,"Enter Password",JOptionPane.OK_CANCEL_OPTION);
        if(action != 0){
            JOptionPane.showMessageDialog(this,"Ακύρωση έναρξης ψηφοφορίας");
            
        }
        else{
            //JOptionPane.showMessageDialog(null,"Your password is "+new String(pwd.getPassword()));
            String pass =new String( pwd.getPassword());
            //JOptionPane.showMessageDialog(null,"Your password is "+new String(pwd.getPassword()));
            
            if (SecureVote.authenticate("admin", pass)){
                JOptionPane.showMessageDialog(this, "Έναρξη ψηφοφορίας!");
                StartVoting.setEnabled(false);
                EndVoting.setEnabled(true);
                VoteNow.setEnabled(true);
                
            }else{
                JOptionPane.showMessageDialog(this, "Λάθος κωδικό! Η Ψηφοφορία δεν μπορεί να αρχίσει!");
            }
        }
        //System.exit(0);
    }//GEN-LAST:event_StartVotingActionPerformed

    private void EndVotingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EndVotingActionPerformed
        JPasswordField pwd = new JPasswordField();
        int action = JOptionPane.showConfirmDialog(this, pwd,"Enter Password",JOptionPane.OK_CANCEL_OPTION);
        if(action != 0){
            JOptionPane.showMessageDialog(this,"Ακύρωση Λήξης ψηφοφορίας");
            
        }
        else{
            //JOptionPane.showMessageDialog(null,"Your password is "+new String(pwd.getPassword()));
            String pass =new String( pwd.getPassword());
            //JOptionPane.showMessageDialog(null,"Your password is "+new String(pwd.getPassword()));
            
            if (SecureVote.authenticate("admin", pass)){
                JOptionPane.showMessageDialog(this, "Λήξη ψηφοφορίας!");
                /*StartVoting.setEnabled(false);
                EndVoting.setEnabled(false);
                VoteNow.setEnabled(false);*/
                endElections();
                SecureVote.results();
                
            }else{
                JOptionPane.showMessageDialog(this, "Λάθος κωδικό! Η Ψηφοφορία συνεχίζεται κανονικά!");
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_EndVotingActionPerformed

    private void VoteNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoteNowActionPerformed
        String user = username.getText();
        String pass = new String (Password.getPassword());
        //System.out.println(user+" - "+pass);
        if (SecureVote.authenticate(user, pass)){
            if(SecureVote.canVote(user)){
                CanditateList.setVisible(true);
                CanditateList.setEnabled(true);
                int[] sel = {};
                CanditateList.setSelectedIndices(sel);
                VoteNow.setEnabled(false);
                PostVote.setEnabled(true);
                username.setEnabled(false);
                Password.setEnabled(false);
            } else{
                JOptionPane.showMessageDialog(this,"Έχετε ήδη ψηφίσει!");
            }
        }else{
             JOptionPane.showMessageDialog(this, "Λάθος στοιχεία. Δεν μπορείτε να ψηφίσετε!");
        }
    }//GEN-LAST:event_VoteNowActionPerformed

    private void PostVoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PostVoteActionPerformed
        int[] sel = CanditateList.getSelectedIndices();
        if (sel.length>SecureVote.maxVotes){
            JOptionPane.showMessageDialog(this,"Εχετε υπερβεί το μέχιστο όριο επιλογών!.");
            return;
        }else{
            SecureVote.recieveVote(username.getText(), sel);
            CanditateList.setVisible(false);
            CanditateList.setEnabled(false);
            VoteNow.setEnabled(true);
            PostVote.setEnabled(false);
            username.setEnabled(true);
            Password.setEnabled(true);
        }
    }//GEN-LAST:event_PostVoteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> CanditateList;
    private javax.swing.JButton EndVoting;
    private javax.swing.JPasswordField Password;
    private javax.swing.JButton PostVote;
    private javax.swing.JButton StartVoting;
    private javax.swing.JLabel Title;
    private javax.swing.JButton VoteNow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
    public void endElections(){
            CanditateList.setVisible(false);
            CanditateList.setEnabled(false);
            VoteNow.setEnabled(false);
            PostVote.setEnabled(false);
            username.setEnabled(false);
            Password.setEnabled(false);
            StartVoting.setEnabled(false);
            EndVoting.setEnabled(false);
            VoteNow.setEnabled(false);
    }
}
